In [8]:
import networkx as nx
import matplotlib.pyplot as plt
import numpy as np

n = 10

G = nx.random_graphs.barabasi_albert_graph(n, 2)   #生成一个BA无标度网络G


In [12]:
# generate laplace matrix
K = np.zeros(shape=(n, n))
A = np.zeros(shape=(n, n))

for (u, v) in G.edges:
    A[u, v] += 1
    A[v, u] += 1
for vertex in nx.nodes(G):
    print('vertex: ', vertex, '->', G.degree[vertex])
    K[vertex, vertex] = G.degree[vertex]
    
L = K - A 
print(L)

vertex:  0 -> 2
vertex:  1 -> 4
vertex:  2 -> 3
vertex:  3 -> 4
vertex:  4 -> 6
vertex:  5 -> 4
vertex:  6 -> 3
vertex:  7 -> 2
vertex:  8 -> 2
vertex:  9 -> 2
[[ 2.  0. -1. -1.  0.  0.  0.  0.  0.  0.]
 [ 0.  4. -1. -1. -1.  0.  0. -1.  0.  0.]
 [-1. -1.  3.  0.  0. -1.  0.  0.  0.  0.]
 [-1. -1.  0.  4. -1. -1.  0.  0.  0.  0.]
 [ 0. -1.  0. -1.  6.  0. -1. -1. -1. -1.]
 [ 0.  0. -1. -1.  0.  4. -1.  0. -1.  0.]
 [ 0.  0.  0.  0. -1. -1.  3.  0.  0. -1.]
 [ 0. -1.  0.  0. -1.  0.  0.  2.  0.  0.]
 [ 0.  0.  0.  0. -1. -1.  0.  0.  2.  0.]
 [ 0.  0.  0.  0. -1.  0. -1.  0.  0.  2.]]


In [14]:
eigh_vals, eigh_vectors = np.linalg.eig(L)
print(eigh_vals)
print(eigh_vectors)

[7.30905458e+00 6.10707692e+00 1.39930857e-15 4.57837837e+00
 1.05107151e+00 1.48418056e+00 1.68417387e+00 2.87436201e+00
 3.57423346e+00 3.33746872e+00]
[[-0.06834143 -0.20080091 -0.31622777 -0.08196849  0.58311801  0.24845594
   0.28926639 -0.52671592 -0.26300093 -0.12750861]
 [ 0.10179634 -0.56035317 -0.31622777 -0.46474557  0.11645256 -0.30930175
   0.01653814  0.20801171  0.44198256  0.10739482]
 [ 0.0475434   0.38893164 -0.31622777 -0.03632961  0.36622489  0.10585812
   0.06522452  0.47829634 -0.17327488  0.58032709]
 [ 0.31528498  0.43577316 -0.31622777  0.2476754   0.1871124   0.02230028
   0.02613337 -0.01775595  0.58729974 -0.40978832]
 [-0.83842811  0.29023297 -0.31622777 -0.20059196 -0.16196504 -0.10435833
  -0.02530378 -0.08007896  0.15055235 -0.07565533]
 [-0.23832202 -0.44728645 -0.31622777  0.60405593  0.01417556  0.22130762
  -0.21998041  0.37879639 -0.0794814  -0.17572846]
 [ 0.22297828  0.07952244 -0.31622777 -0.40423894 -0.35579105  0.20188635
   0.17584884  0.30748

In [15]:
# Capocci algorithm -> Normal matrix
N = np.dot(np.linalg.inv(K), A)
print(N)


[[0.         0.         0.5        0.5        0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.25       0.25       0.25       0.
  0.         0.25       0.         0.        ]
 [0.33333333 0.33333333 0.         0.         0.         0.33333333
  0.         0.         0.         0.        ]
 [0.25       0.25       0.         0.         0.25       0.25
  0.         0.         0.         0.        ]
 [0.         0.16666667 0.         0.16666667 0.         0.
  0.16666667 0.16666667 0.16666667 0.16666667]
 [0.         0.         0.25       0.25       0.         0.
  0.25       0.         0.25       0.        ]
 [0.         0.         0.         0.         0.33333333 0.33333333
  0.         0.         0.         0.33333333]
 [0.         0.5        0.         0.         0.5        0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.5        0.5
  0.         0.         0.         0.        ]
 [0.         0.   

In [17]:
print(np.linalg.eigvals(N))

[ 1.         -0.8631845   0.58684637  0.42623776  0.22727927  0.04479677
 -0.10761851 -0.29559904 -0.53881098 -0.47994713]


In [6]:
import numpy as np
M = np.array([[0., 0.5, 0.], [1., 0., 1.], [0., 0.5, 0.]])

M2 = np.array([[0.5, 0, 0.5], [0., 1., 0.], [0.5, 0, 0.5]])

I = np.array([[1., 0., 0.], [0., 1., 0.], [0., 0., 1.]])

In [8]:
print(np.linalg.inv(I-M))

LinAlgError: Singular matrix